Add SSL loadbalancer article
CloudTutorials/OpenStack-Docs pull request #36
Opened 2024-03-12 15:02 UTC by RobertJansen1

2024-03-13 15:16 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 2**: Await the update of the load balancer's Operating Status to ONLINE and the DNS to
Please add two spaces here to add an enter

2024-03-13 15:16 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 1**: Create an A record in DNS for the domain to point to the floating IP address
Please add two spaces here to add an enter

2024-03-13 15:17 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 3**: Verify the SSL of the load balancer to have your URL checked with the
Please add two spaces here to add an enter

2024-03-13 15:19 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the enter whitespace

2024-03-13 15:19 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace
![image](https://github.com/CloudTutorials/OpenStack-Docs/assets/31192098/eba406b0-9e16-46f5-8923-1e31e46bbd31)

2024-03-13 15:19 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace

2024-03-13 15:19 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace

2024-03-13 15:19 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Prerequisites**
Please add two spaces here to add an a line break

2024-03-13 15:20 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +## Creating the loadbalancer
Maybe add line breaks behind the steps so the style of the steps is the same throughout the article (Optional)

2024-03-13 15:20 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace

2024-03-13 15:20 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace

2024-03-13 15:20 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 3**
Please remove the whitespace

2024-03-13 15:20 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 4**
Please add two spaces here to add an a line break

2024-03-13 15:21 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 5**
Please add two spaces here to add an a line break

2024-03-13 15:21 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +**Step 6**
Please add two spaces here to add an a line break

2024-03-13 15:25 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +certificate=certificate.pem
Please add some comments and/or some whitespace so the article is more readable 

An example of this you can find at the bottom of the [Resize Volume](https://cloudtutorials.eu/articles/resize-volume) article (Check the last code block)

2024-03-13 15:25 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +name="${domain}_passphrase"
Please add some comments and/or some whitespace so the article is more readable 

An example of this you can find at the bottom of the [Resize Volume](https://cloudtutorials.eu/articles/resize-volume) article (Check the last code block)

2024-03-13 15:25 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +certificate=intermediate.pem
Please add some comments and/or some whitespace so the article is more readable 

An example of this you can find at the bottom of the [Resize Volume](https://cloudtutorials.eu/articles/resize-volume) article (Check the last code block)

2024-03-13 15:26 UTC, houtknots commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +
Please remove the whitespace below the command

2024-03-13 15:27 UTC, houtknots requested changes
Needs some change to make the article better readable

2024-03-13 15:29 UTC, bkranendonk commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> + - openssl tooling installed on the OpenStack CLI server
OpenSSL

2024-03-13 15:30 UTC, bkranendonk commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +name="${domain}_container"
Maybe code comments here

2024-03-13 15:30 UTC, bkranendonk commented on _posts/loadbalancers/2024-03-08-create-a-ssl-loadbalancer.md
> +* **Flavor**: Choose a flavor to your liking for this tutorial we use the Medium flavor
Interpunction

2024-03-26 14:41 UTC, houtknots approved these changes

2024-03-26 14:41 UTC, merged